### ISSUE TITLE
No module named lib.packager

### ISSUE THREAD

**Issue by bostjan39** [mgeeky/PackMyPayload#10]
Any clues why it's not anywhere to be found? 
I use Python 3.7

**Comment by mgeeky** [comment]
Hi there,

Thanks for dropping it in, can you show me what exception stacktrace are you getting?
`lib.packager` can be found in `lib/packager.py` file.

Best,
Mariusz

**Comment by bostjan39** [comment]
Hi, thanks for quick reply:)
This is my cmd message I get.
Btw, I check and I don't have a packager.py in my Lib folder. Where can I get it, I looked online but no luck so far...:)

python isopack.py msg.exe msg.iso

Traceback (most recent call last):
  File "isopack.py", line 10, in <module>
    import lib.packager
ModuleNotFoundError: No module named 'lib.packager'

**Comment by mgeeky** [comment]
I don't know what's isopack but this doesn't look like it belongs to this repository. As I said, you'll find `lib.packager` in `lib/packager.py`. Kindly review contents of this repository.

Let me know how else can I help.

Regards,
Mariusz.

**Comment by mgeeky** [comment]
https://github.com/mgeeky/PackMyPayload/blob/master/lib/packager.py

**Comment by bostjan39** [comment]
Oh, I'm a total idiot, lol:)
Sorry, just starting out with github.
Thx!
