### ISSUE TITLE
Python Issues

### ISSUE THREAD

**Issue by Offensive-Panda** [mgeeky/PackMyPayload#2]
I am facing problems to install requirements. can you please mention the python supported version for this or upload the compiled EXE.

**Comment by mgeeky** [comment]
Hi, I was testing the tool on Python 3.9 and 3.10. 
What problems are you facing exactly?

**Comment by Offensive-Panda** [comment]
![issue](https://user-images.githubusercontent.com/76246439/154412342-2b4081e2-ada9-4262-a36e-c5d684dad34d.PNG)

**Comment by Offensive-Panda** [comment]
> Hi, I was testing the tool on Python 3.9 and 3.10. What problems are you facing exactly?

I am also using python 3.9

**Comment by Offensive-Panda** [comment]
All issues are resolved. In requirement file you need to remove ctypes because it standard library and also change zipfile to zipfile2

**Comment by Offensive-Panda** [comment]
Kindly remove cytpes form requirement file it is standard library and change zipfile to zipfile2. Issues Resolved

**Comment by mgeeky** [comment]
Hi! Thank you for your bug report - its addressed now in [75f6270](https://github.com/mgeeky/PackMyPayload/commit/75f6270d0417d749b56c718d0d8ad0003c74d785).

Let me know if that fixes the issue. :-)
